from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from co2patent.pipeline import (  # noqa: E402
    infer_group,
    infer_target,
    load_model_bundle,
    load_table,
    save_train_result,
    screen_candidates,
    train_best_model,
)


@dataclass(frozen=True)
class EvidenceRun:
    name: str
    group: str | None
    exclude_columns: tuple[str, ...] = ()
    note: str = ""


RUNS = (
    EvidenceRun(
        name="zenodo_random_full",
        group=None,
        note="Random row split; useful as a leakage-sensitive upper-bound baseline.",
    ),
    EvidenceRun(
        name="zenodo_solvent_holdout_full",
        group="solvent_id",
        note="Solvent-held-out split with ion identity codes and derived SMILES descriptors.",
    ),
    EvidenceRun(
        name="zenodo_solvent_holdout_structure_only",
        group="solvent_id",
        exclude_columns=("cation_code", "anion_code"),
        note="Solvent-held-out split using operating conditions and derived SMILES descriptors.",
    ),
    EvidenceRun(
        name="zenodo_cation_holdout_no_cation_code",
        group="cation_code",
        exclude_columns=("cation_code",),
        note="Cation-family holdout; cation identity code withheld from features.",
    ),
    EvidenceRun(
        name="zenodo_anion_holdout_no_anion_code",
        group="anion_code",
        exclude_columns=("anion_code",),
        note="Anion-family holdout; anion identity code withheld from features.",
    ),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run repeatable patent-evidence ML benchmarks.")
    parser.add_argument(
        "--data",
        default="data/processed/zenodo_3251643_co2capacity.csv",
        help="Prepared training CSV.",
    )
    parser.add_argument("--target", default="ln_co2_solubility", help="Target column.")
    parser.add_argument(
        "--candidates",
        default="data/processed/zenodo_candidate_examples.csv",
        help="Candidate screen CSV.",
    )
    parser.add_argument("--out", default="runs/evidence_suite", help="Output directory.")
    parser.add_argument("--test-size", type=float, default=0.25)
    parser.add_argument("--calibration-size", type=float, default=0.25)
    parser.add_argument("--alpha", type=float, default=0.10)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def write_markdown_summary(summary: pd.DataFrame, out_dir: Path) -> None:
    columns = [
        "run",
        "group",
        "excluded_columns",
        "best_model",
        "r2",
        "mae",
        "rmse",
        "interval_coverage",
        "mean_interval_width",
        "test_rows",
    ]
    ordered = summary[columns].copy()
    for column in ("r2", "mae", "rmse", "interval_coverage", "mean_interval_width"):
        ordered[column] = ordered[column].map(lambda value: f"{float(value):.4f}")
    ordered["test_rows"] = ordered["test_rows"].map(lambda value: f"{int(float(value))}")
    table_rows = [columns]
    table_rows.extend([[str(row[column]) for column in columns] for _, row in ordered.iterrows()])
    widths = [
        max(len(row[index]) for row in table_rows)
        for index in range(len(columns))
    ]
    header = "| " + " | ".join(
        table_rows[0][index].ljust(widths[index])
        for index in range(len(columns))
    ) + " |"
    separator = "| " + " | ".join("-" * widths[index] for index in range(len(columns))) + " |"
    body = [
        "| " + " | ".join(
            row[index].ljust(widths[index])
            for index in range(len(columns))
        ) + " |"
        for row in table_rows[1:]
    ]

    lines = [
        "# Evidence Suite Summary",
        "",
        "These runs are generated by `scripts/run_evidence_suite.py`.",
        "",
        header,
        separator,
        *body,
        "",
        "## Notes",
        "",
    ]
    for _, row in summary.iterrows():
        lines.append(f"- `{row['run']}`: {row['note']}")
    (out_dir / "summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    df = load_table(args.data)
    target = infer_target(df, args.target)
    summary_rows: list[dict[str, object]] = []

    for run in RUNS:
        group = infer_group(df, run.group) if run.group else None
        run_dir = out_dir / run.name
        run_dir.mkdir(parents=True, exist_ok=True)
        result, leaderboard, predictions = train_best_model(
            df=df,
            target=target,
            group=group,
            exclude_columns=list(run.exclude_columns),
            test_size=args.test_size,
            calibration_size=args.calibration_size,
            alpha=args.alpha,
            random_state=args.seed,
        )
        save_train_result(result, run_dir)
        leaderboard.to_csv(run_dir / "leaderboard.csv", index=False)
        predictions.to_csv(run_dir / "test_predictions.csv", index=False)
        metadata = {
            "run": run.name,
            "note": run.note,
            "target": target,
            "group": group,
            "excluded_columns": list(run.exclude_columns),
            "best_model": result.model_name,
            "metrics": result.metrics,
            "calibration_qhat": result.calibration_qhat,
            "features": result.feature_columns,
        }
        (run_dir / "metrics.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        summary_rows.append(
            {
                "run": run.name,
                "note": run.note,
                "target": target,
                "group": group or "NONE",
                "excluded_columns": ",".join(run.exclude_columns) or "NONE",
                "best_model": result.model_name,
                "calibration_qhat": result.calibration_qhat,
                **result.metrics,
            }
        )
        print(f"{run.name}: {result.model_name} {json.dumps(result.metrics, sort_keys=True)}")

    summary = pd.DataFrame(summary_rows)
    summary.to_csv(out_dir / "summary.csv", index=False)
    write_markdown_summary(summary, out_dir)

    candidates_path = Path(args.candidates)
    if candidates_path.exists():
        bundle = load_model_bundle(out_dir / "zenodo_solvent_holdout_full" / "model.joblib")
        candidates = load_table(candidates_path)
        ranked = screen_candidates(bundle, candidates)
        ranked.to_csv(out_dir / "candidate_ranking.csv", index=False)
        print(f"Candidate ranking saved to: {out_dir / 'candidate_ranking.csv'}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
