"""Post-process E6 external-holdout predictions into the canonical results doc.

Cheap + re-runnable (reads the saved ``runs/external_holdout/predictions/*.csv``;
does NOT re-fit anything). Emits per-set and pooled-by-concatenation metrics with
both calibration-sensitive (R²/RMSE/MAE) and calibration-free (Spearman/Pearson)
association, so the honest "captures trend but miscalibrated out-of-distribution"
distinction is visible.

    .venv_mac/bin/python -m sota_pka.external_summary
"""
from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


RUN_DIR = _repo_root() / "sota_pka" / "runs" / "external_holdout"
PRED_DIR = RUN_DIR / "predictions"

TASK_SETS = {
    "acidic": ["novartis_acidic", "AvLiLuMoVe_123_acidic", "SAMPL7_acidic"],
    "basic": ["novartis_basic", "AvLiLuMoVe_123_basic"],
}
# Reproduced OP2-test (in-distribution) anchors from the full run, for the gap column.
OP2_TEST = {
    "acidic": {"qlattice": 0.448, "lightgbm": 0.832, "random_forest": 0.776},
    "basic": {"qlattice": 0.452, "lightgbm": 0.837, "random_forest": 0.801},
}
MODELS = ["qlattice", "lightgbm", "random_forest", "y_random_lightgbm"]
MODEL_LABEL = {
    "qlattice": "QLattice (symbolic)",
    "lightgbm": "LightGBM (ceiling)",
    "random_forest": "RandomForest",
    "y_random_lightgbm": "y-random (control)",
}


def _assoc(y: np.ndarray, p: np.ndarray) -> dict:
    n = len(y)
    out = {"n": n}
    out["r2"] = float(r2_score(y, p)) if n > 1 else float("nan")
    out["rmse"] = float(math.sqrt(mean_squared_error(y, p))) if n > 0 else float("nan")
    out["mae"] = float(mean_absolute_error(y, p)) if n > 0 else float("nan")
    if n > 2 and np.std(p) > 0:
        out["spearman"] = float(spearmanr(y, p).correlation)
        out["pearson"] = float(pearsonr(y, p)[0])
        out["slope"] = float(np.polyfit(p, y, 1)[0])
    else:
        out["spearman"] = out["pearson"] = out["slope"] = float("nan")
    return out


def _load(set_name: str, rep: str, model: str) -> pd.DataFrame | None:
    f = PRED_DIR / f"{set_name}__{rep}__{model}.csv"
    return pd.read_csv(f) if f.exists() else None


def build(rep: str = "neutral") -> tuple[pd.DataFrame, pd.DataFrame]:
    per_set_rows, pooled_rows = [], []
    for task, sets in TASK_SETS.items():
        pooled = {m: [] for m in MODELS}
        for s in sets:
            for m in MODELS:
                d = _load(s, rep, m)
                if d is None:
                    continue
                a = _assoc(d["y_true"].to_numpy(), d["y_pred"].to_numpy())
                per_set_rows.append({"task": task, "set": s, "model": m, **a})
                pooled[m].append(d)
        for m in MODELS:
            if not pooled[m]:
                continue
            d = pd.concat(pooled[m], ignore_index=True)
            a = _assoc(d["y_true"].to_numpy(), d["y_pred"].to_numpy())
            pooled_rows.append({"task": task, "set": "POOLED", "model": m, **a})
    return pd.DataFrame(per_set_rows), pd.DataFrame(pooled_rows)


def _fmt(x: float) -> str:
    return "—" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{x:.3f}"


def _table(df: pd.DataFrame, task: str) -> list[str]:
    sub = df[df["task"] == task]
    lines = ["| set | model | n | R² | RMSE | MAE | Spearman ρ | Pearson r | slope |",
             "|---|---|---:|---:|---:|---:|---:|---:|---:|"]
    set_order = TASK_SETS[task] + ["POOLED"]
    for s in set_order:
        block = sub[sub["set"] == s]
        for m in MODELS:
            r = block[block["model"] == m]
            if r.empty:
                continue
            r = r.iloc[0]
            lines.append(
                f"| {s} | {MODEL_LABEL[m]} | {int(r['n'])} | {_fmt(r['r2'])} | {_fmt(r['rmse'])} | "
                f"{_fmt(r['mae'])} | {_fmt(r['spearman'])} | {_fmt(r['pearson'])} | {_fmt(r['slope'])} |")
    return lines


def main() -> None:
    per_set, pooled = build("neutral")
    allrows = pd.concat([per_set, pooled], ignore_index=True)
    allrows.to_csv(RUN_DIR / "external_summary_neutral.csv", index=False)

    L: list[str] = []
    L.append("# E6 — External-holdout generalization audit (H3)\n")
    L.append("*Neutral-representation results (external SMILES standardized to the OP2 "
             "neutral-structure convention via RDKit Uncharger + largest-fragment parent). "
             "Generated by `sota_pka.external_summary` from `runs/external_holdout/predictions/`.*\n")
    L.append("**In-distribution anchors (reproduced OP2-test R²):** "
             "acidic — QLattice 0.448, LightGBM 0.832; basic — QLattice 0.452, LightGBM 0.837. "
             "These reproduce the recorded leakage-safe models (acidic exact; basic within seed variance of 0.470).\n")
    for task in ("acidic", "basic"):
        L.append(f"\n## External {task} sets\n")
        L += _table(allrows, task)
        L.append("")
    L.append("\n## Reading the table\n")
    L.append("- **R²/RMSE/MAE** are calibration-sensitive; **Spearman/Pearson** measure rank/linear "
             "association independent of scale, and **slope** is the least-squares calibration gain "
             "(1.0 = perfectly scaled).")
    L.append("- The **y-random control** (LightGBM on shuffled OP2 labels) is the chance floor; a model "
             "only carries real external signal if its Spearman exceeds the control's on the same set.")
    L.append("- **Representation sensitivity:** the same scoring on *raw ionized* external SMILES (see "
             "`external_holdout_report.md`) collapses every model (R² down to −2…−62), confirming "
             "protonation-state standardization is a first-order requirement for external pKa benchmarking.")
    L.append("\n## Honest verdict (H3)\n")
    L.append("Partially rejected / nuanced. The compact symbolic formulas transfer **weak-to-moderate, "
             "above-chance** rank signal to external blind sets (Spearman 0.27–0.58 on 4/5 sets vs a "
             "chance floor of 0.07–0.22) — so the electronic structure they encode is not purely "
             "OP2-split-specific — but they are **poorly calibrated out-of-distribution** (low/negative "
             "R², slopes 0.26–0.76) and are out-ranked by the LightGBM ceiling on the larger sets "
             "(Spearman 0.67–0.73). The symbolic model does not match in-distribution accuracy externally; "
             "the GBM degrades from R²≈0.84 to 0.40–0.58 but retains the better external profile.")
    out = RUN_DIR / "RESULTS_external_holdout.md"
    out.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))
    print(f"\nWrote {out}\n      {RUN_DIR/'external_summary_neutral.csv'}")


if __name__ == "__main__":
    main()
